"""compliance score calculation

Revision ID: 30353fb6f028
Revises: fc993cae0b2f
Create Date: 2026-05-11 01:08:29.219308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30353fb6f028'
down_revision: Union[str, Sequence[str], None] = 'fc993cae0b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintainance_tasks', sa.Column('completed_on', sa.DateTime(), nullable=True))
    op.add_column('ship_crew_assignments', sa.Column('drills_total', sa.Integer(), nullable=True))
    op.add_column('ship_crew_assignments', sa.Column('drills_attended', sa.Integer(), nullable=True))
    op.add_column('ship_crew_assignments', sa.Column('tasks_total', sa.Integer(), nullable=True))
    op.add_column('ship_crew_assignments', sa.Column('tasks_completed', sa.Integer(), nullable=True))
    op.add_column('ship_crew_assignments', sa.Column('compliance_score', sa.Integer(), nullable=True))
    op.add_column('ships', sa.Column('compliance_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ships', 'compliance_score')
    op.drop_column('ship_crew_assignments', 'compliance_score')
    op.drop_column('ship_crew_assignments', 'tasks_completed')
    op.drop_column('ship_crew_assignments', 'tasks_total')
    op.drop_column('ship_crew_assignments', 'drills_attended')
    op.drop_column('ship_crew_assignments', 'drills_total')
    op.drop_column('maintainance_tasks', 'completed_on')
    # ### end Alembic commands ###
