"""added assigne user id columns nullable

Revision ID: 450f992fcbe5
Revises: 3f1ce1ab7993
Create Date: 2026-05-08 09:50:16.837492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450f992fcbe5'
down_revision: Union[str, Sequence[str], None] = '3f1ce1ab7993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintainance_tasks', 'assigned_to_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintainance_tasks', 'assigned_to_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
