"""maintainance task new columns

Revision ID: 5da3b68d585b
Revises: b1f7cb135b52
Create Date: 2026-05-08 02:18:08.444592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da3b68d585b'
down_revision: Union[str, Sequence[str], None] = 'b1f7cb135b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintainance_tasks', sa.Column('type', sa.String(), nullable=False))
    op.add_column('maintainance_tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintainance_tasks', 'due_date')
    op.drop_column('maintainance_tasks', 'type')
    # ### end Alembic commands ###
