"""ship type and imo columns added

Revision ID: b1f7cb135b52
Revises: a198f880d454
Create Date: 2026-05-08 01:33:20.261485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f7cb135b52'
down_revision: Union[str, Sequence[str], None] = 'a198f880d454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ships', sa.Column('imo', sa.String(), nullable=True))
    op.add_column('ships', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ships', 'description')
    op.drop_column('ships', 'imo')
    # ### end Alembic commands ###
