"""add columns to users table

Revision ID: c137169504eb
Revises: 476b41aa33a6
Create Date: 2026-05-08 07:09:24.670280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c137169504eb'
down_revision: Union[str, Sequence[str], None] = '476b41aa33a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(), server_default='crew', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('user', 'designation')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
